#!/bin/sh
. "$(dirname "$0")/common.sh"

echo '👷 Checking lint issues before committing 🛁🧽'
echo 'Please be patient, this may take a while...'

# Verifica e interrompe se houver erro
pnpm lint
if [ $? -ne 0 ]; then
  echo '🔨❌ Yoo, you have a problem in your code. Fixing it 🧼🧹'
  exit 1
fi

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'
pnpm lint-staged
